insert into  Province (name, RegionId ) values
('Kénitra Province',7),
('Khémisset Province',7),
('Rabat Prefecture',7),
('Salé Prefecture',7),
('Sidi Kacem Province',7),
('Sidi Slimane Province',7),
('Skhirate-Témara Prefecture',7),
('Agadir-Ida Ou Tanane Prefecture',8),
('Chtouka Aït Baha Province',8),
('Inezgane-Aït Melloul Prefecture',8),
('Taroudant Province',8),
('Tata Province',8),
('Tiznit Province',8),
('Al Hoceïma Province',9),
('Chefchaouen Province',9),
('Fahs-Anjra Province',9),
('Larache Province',9),
('Mdiq-Fnideq Prefecture',9),
('Ouezzane Province',9),
('Tangier-Assilah Prefecture',9),
('Tétouan Province',9),
('Aousserd Province',10),
('Oued Ed-Dahab Province',10),
('Assa-Zag Province',11),
('Guelmim Province',11),
('Sidi Ifni Province',11),
('Tan-Tan Province',11),
('Boujdour Province',12),
('Es Semara Province',12), 
('Laâyoune Province',12),
('Tarfaya Province',12);
